# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mean_assembler": "01_twoDim.ipynb",
         "kernMat": "01_twoDim.ipynb",
         "BigPhiMat": "01_twoDim.ipynb",
         "cov_assembler": "01_twoDim.ipynb",
         "m_post": "01_twoDim.ipynb",
         "sample_gp": "01_twoDim.ipynb",
         "gen_sensor": "01_twoDim.ipynb",
         "MyExpression": "01_twoDim.ipynb",
         "fem_cov_assembler_post": "01_twoDim.ipynb",
         "m_post_fem_assembler": "01_twoDim.ipynb",
         "c_post": "01_twoDim.ipynb",
         "post_fem_cov_assembler": "01_twoDim.ipynb",
         "c_post_fem_assembler": "01_twoDim.ipynb",
         "wass": "06_maxDist.ipynb"}

modules = ["oneDim.py",
           "twoDim.py",
           "maxDist.py"]

doc_url = "https://YanniPapandreou.github.io/statFEM/"

git_url = "https://github.com/YanniPapandreou/statFEM/tree/master/"

def custom_doc_links(name): return None
