# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mean_assembler": "00_oneDim.ipynb",
         "kernMat": "00_oneDim.ipynb",
         "BigPhiMat": "00_oneDim.ipynb",
         "cov_assembler": "00_oneDim.ipynb"}

modules = ["oneDim.py"]

doc_url = "https://YanniPapandreou.github.io/statFEM/"

git_url = "https://github.com/YanniPapandreou/statFEM/tree/master/"

def custom_doc_links(name): return None
